### ISSUE TITLE
Latest nightly build cannot be uninstalled (3.0.510)

### ISSUE THREAD

**Issue by UCyborg** [processhacker2/processhacker#129]
I was prompted today that the newer version is available, so I updated and ended up with 2 Process Hacker entries in Programs & Features. Then I wanted to clean everything up so I'd have 1 entry and I figured the new installler doesn't allow uninstallation at all.

I could get rid of the old entry, which didn't remove any of the updated Process Hacker files, but then trying to uninstall the program through the latest entry results in the message that it may have been uninstalled already and whether do I want to remove the entry from Programs & Features list.

My main OS is Windows 8.1 x64 and re-installation doesn't help. I also tried it on updated Windows 10 CU virtual machine where Process Hacker wasn't installed previously and I experience the similar issue there. When I go to Programs & Features to uninstall it, nothing happens when double-clicking its entry.

**Comment by UCyborg** [comment]
I noticed there's a link to a new build 511, but can't download it yet, I get some error in XML saying BlobNotFound. I hope it gets resolved.

**Comment by UCyborg** [comment]
Uninstallation seems to work OK now, though there is a copy of installer left in Process Hacker installation directory and folders plugins and x86. The old installer purged everything except for files user put anywhere under the install dir on their own. If user didn't put anything inside, the whole Process Hacker folder was gone.

I just realized that the installation directory name was changed from Process Hacker 2 to Process Hacker so I might have been looking at the wrong folder before when I said the the updated files haven't been removed.

The change of installer results in 2 separate entries. So those two things are apparently the cause for less smooth transition from older builds.

**Comment by UCyborg** [comment]
Spotted additional problems with installer:

- Create desktop shortcut for all users option doesn't work.
- Set as the default Windows Task Manager option doesn't work.
- If user selects Launch on system startup, the corresponding registry entry persists after uninstall.
- Reset Process Hacker settings option doesn't work (the old installer also offered possibility to reset settings on uninstall).
- Start Process Hacker after setup exits option creates KProcessHacker3 entry in registry, starts associated service then marks it for deletion. I think it shouldn't touch those parts of registry at all unless Install KProcessHacker as a service option is enabled.

**Comment by dmex** [comment]
Spotted additional problems with installer:

- [x] - "Create desktop shortcut for all users" option doesn't work.
- [x] - "Set as the default Windows Task Manager" option doesn't work.
- [x] - If user enables "Launch on system startup" option, the corresponding registry entry persists after uninstall.
- [x] - "Reset Process Hacker settings" option doesn't work (the old installer also offered possibility to reset settings on uninstall).
- [x] - "Start Process Hacker after setup exits" option creates KProcessHacker3 entry in registry, starts associated service then marks it for deletion. I think it shouldn't touch those parts of registry at all unless Install KProcessHacker as a service option is enabled.
- [x] - If Process Hacker is running when attempting installation, installer closes it, but then it gets stuck at "Preparing installation...".

These bugs have been fixed in the latest nightly build 👍

**Comment by UCyborg** [comment]
I see PhOpenKey was already replaced with PhCreateKey today in the repo for setting Process Hacker as default Task Manager.

Other than that, I noticed on 3.0.872 that "Reset Process Hacker settings" doesn't seem to do anything yet. Other available options seem to work as expected.

**Comment by dmex** [comment]
> "Reset Process Hacker settings" doesn't seem to do anything

Thanks for finding that bug, the checkbox was using the wrong resource identifier and its been fixed in the latest nightly 👍
