### ISSUE TITLE
Feature Request: Universal Search

### ISSUE THREAD

**Issue by prasannavl** [processhacker2/processhacker#160]
One of the things I find myself doing very often is switching tabs, hitting Ctrl+K and searching. It would be immensely useful, if there an universal search, either with tree UI that separates and shows all of them. It would be fantastic to monitor all aspects of multiple processes this way.

Or in the interim, a simpler implementation to simply use a prefix: `s:SomeService` or `p:Process`, `d:DiskActivitySearchItem`, `n:NetworkSearchItem`, etc. It is possible I missed some important reason why ":" should be a part of the search itself - but it's just a placeholder for the syntax. A different syntax could work as well.

**Comment by TETYYS** [comment]
implementing Ctrl+Tab, Ctrl+Shift+Tab as hotkeys to switch tabs back and forth might be useful in this case

**Comment by dmex** [comment]
@prasannavl 

You can already search multiple entries using the | character like this:

`SomeService|Process|DiskActivitySearchItem|NetworkSearchItem `

> I missed some important reason why ":" should be a part of the search itself

The : character is used by process filenames and command lines (e.g. C:\process.exe) so we use the | character instead.

At present the search format syntax is just a basic compare algorithm designed to be 'inclusive' instead of 'exclusive' since that returns the most possible entries with the specified input.

As a workaround you can use multiple instances of Process Hacker simultaneously... 

It's fairly easy to use keywords like "p:" and "s:" to limit the search to specific tabs... I just haven't got around to designing a proper search syntax yet 😄 

I can try adding syntax for "p:" and "s:" if you want?

@TETYYS 

Those hotkeys have already been implemented and already do exactly what you suggested? 😄

**Comment by prasannavl** [comment]
@dmex 

> SomeService|Process|DiskActivitySearchItem|NetworkSearchItem

I do use this frequently, and it's fantastic to say the least! :) Locks you down to the exact ones you care about spot on. However, what I meant was a view that spans across process, services, disk usage, and network sockets. But I think that view is a time consuming undertaking. But the ability to search across all of them instead of just the active tab would be simpler to implement while without an exclusive view.

> I can try adding syntax for "p:" and "s:" if you want?

I really appreciate your support to get right on it here. But in the case where you haven't given it some thought, I'd probably just sleep on it - see if someone comes up with something better. To be honest, I didn't give it much thought - just threw it in there, since it would be a valuable addition. 

Coming to think of it, I think `:` may not be the best idea. Considering commandline will have the ":" quite a lot due to the drive root, and will interfere with path search without escaping.

**Comment by prasannavl** [comment]
@dmex I just tried the shortcuts mentioned above, the search text is persistent (Somehow, I had never tried that before)! I think that should be more than sufficient instead of convolution the syntax, that is blissfully simple, and very productive. 

If you agree, shall I just close this? Or keep this open if there's any intent to think about a view that spans across all of the activities in the future.

**Comment by TETYYS** [comment]
> Those hotkeys have already been implemented and already do exactly what you suggested?

wow nice, thanks

**Comment by dmex** [comment]
> Coming to think of it, I think : may not be the best idea

We would use one of the 'banned' characters filesystem characters like ! or ? instead of using the : character.

For example: p!name or s?name

> I think that should be more than sufficient instead of convoluting the syntax, that is blissfully simple, and very productive. (I feel bad now, that I suggested it)

I do want to support this at some stage since it would be handy... there just hasn't been any requests for it yet 😄
