### ISSUE TITLE
Why the cmdline usage can't work

### ISSUE THREAD

**Issue by alexunder** [processhacker2/processhacker#172]
I want to use PH in batch file to kill some malwares, but it can't kill

```bash
ProcessHacker.exe -c -ctype process -cobject malware.exe -caction terminate
```
Then it showed the error message Box: Unable to execute the command "Access denied".

How to fix it?

**Comment by dmex** [comment]
This is by design. If malware infected your machine then it could just invoke the commandline and terminate anything it wants... As such the commandline is unable to use more advanced features for terminating rootkits etc.... You will need to use the UI when you get an access denied error.

If you want to use the commandline then you will need to remove various security features and additionally sign the driver yourself (since our signed driver doesn't work with unofficial custom builds).
