### ISSUE TITLE
[enhancement]Network tab additions and other

### ISSUE THREAD

**Issue by ajloveslily14** [processhacker2/processhacker#177]
I was wondering if there could be a column in the network tab that shows how much data is being transferred through a connection listed, if you can even get that info.

I was also wondering if there was a way to make it so valves "VAC" doesn't think process hacker is a cheating tool and blocks access to VAC servers while its running. What I have been doing is closing processes hacker, closing steam, and using rammap to empty the standby and modified paged memory, if it's not done that way you get blocked.

**Comment by dmex** [comment]
> a column in the network tab that shows how much data is being transferred through a connection listed

You need to run Process Hacker as administrator and add the "Total rate" and "Total Bytes" columns.

> make it so valves "VAC" doesn't think process hacker is a cheating tool

I've tried removing the features Valve complained about but they continued to target Process Hacker despite those changes and ignored my follow up emails...  See my post here:
https://wj32.org/processhacker/forums/viewtopic.php?f=24&p=8716&#p8709

**Comment by ajloveslily14** [comment]
>I've tried removing the features Valve complained about but they continued to target Process Hacker despite those changes and ignored my follow up emails... See my post here:
https://wj32.org/processhacker/forums/viewtopic.php?f=24&p=8716&#p8709

I have the feeling that they are blocking it because it has hacker in it and that spooked them. Also maybe because it has a dll injector? Who knows, despite being as big as they are their technical know-how doesn't show it.

>You need to run Process Hacker as administrator and add the "Total rate" and "Total Bytes" columns.

I have done that, and I do not see those options listed, here is a screenshot:
![6q2gtlh 1](https://user-images.githubusercontent.com/5560560/32696466-66007cf6-c73e-11e7-9dca-3ee5ea024125.png)

note that I am on version 2.39.124 which at the time posting seems to be the latest release

**Comment by dmex** [comment]
>  I am on version 2.39.124 which at the time posting seems to be the latest release

You need the ExtendedTools plugin installed (included with the setup.exe or bin.zip release)?

You can also install the Nightly release which includes hundreds of additions and changes since the v2.39 release: https://wj32.org/processhacker/nightly.php

>I have the feeling that they are blocking it because it has hacker in it and that spooked them.

Valve banned Process Hacker back in 2013 for two days before unbanning it. At that time I was a developer for the Origin team at Electronic Arts and I spoke with Valve about it... They didn't have issues with any of these features back in 2013 and VAC developers were more than happy to discuss it with us.

This time they've used an anonymous email address and just demanded changes outright without any discussion and have ignored every follow up email.

> Also maybe >because it has a dll injector? 

You can very easily disable DLL injection using the [SetProcessMitigationPolicy](https://msdn.microsoft.com/en-us/library/windows/desktop/hh769088.aspx) function or the [ObRegisterCallbacks](https://msdn.microsoft.com/en-us/library/windows/hardware/ff558692.aspx) functions.

DLL Injection and Memory features included with Process Hacker are used by the security community to test their companies products and are also used to demonstrate security enhancements at major events (for example: https://youtu.be/LqaWIn4y26E?t=42m40s) - We're not going to remove features that are required by the security community and developers to test their own products when those exact same features can be easily disabled (especially when those demands come from anonymous Valve email addresses and also ignore replies from the development team...).

If you can inject a DLL or edit memory using Process Hacker and if thats a problem for your product - The solution to that problem as recommended by Microsoft is using the the SetProcessMitigationPolicy and/or ObRegisterCallbacks functions to restrict access to your process - Those functions will block everything including Process Hacker.

It's no coincidence that BattlEye and EAC anti-cheat use those functions and also don't block Process Hacker.

> Who knows, despite being as big as they are their technical know-how >doesn't show it.

Valve would know about those functions (they've been available since 2006) but for unknown reasons decided against using them.
