### ISSUE TITLE
Create a button to Show/Enable Copy-Paste of needed "Text" for issue creation

### ISSUE THREAD

**Issue by stdedos** [processhacker2/processhacker#202]
e.g. PH Version, Windows Version, Plugins etc etc

PH 3.0.1123 (But I guess it's an enhancement, so no version needed)

**Comment by dmex** [comment]
Your description is a bit vague... A 'github issue template' or something else?

**Comment by stdedos** [comment]
A _pre-filled Github Issue Template_ that can be easily generated from PH (in the Help > 'Report issue...' or Help > About > 'Report issue...')

**Comment by dmex** [comment]
> Github Issue Template that can be easily generated from PH

Including these sort of things in the desktop client is unnecessary since most people have been using the forum as the main bug reporting mechanism: https://wj32.org/processhacker/forums/

I'll look at adding an issue template for Github issues in the future but right now its pointless since we're lucky to get more than 1 issue a month and if I need more info then I'll just ask 😄
