### ISSUE TITLE
SBIE2035: Out of memory

### ISSUE THREAD

**Issue by stdedos** [processhacker2/processhacker#233]
Windows 10 / PE  3.0.1254 (PE 3.0.1216 worked)

https://www.sandboxie.com/SBIE2305

![image](https://user-images.githubusercontent.com/133706/35721432-b01736c0-07fa-11e8-90d0-766f536d6f09.png)

Program starts, PE/Avast complain about the kernel driver ... and then nothing
TaskManager is overriden, so I don't know what happens

Disabling `SbieSupport.dll` works

**Comment by diversenok** [comment]
Can you tell us more about how to reproduce this problem?

 - What version of `SbieSupport.dll` do you have?
 - Are there are any programs running sandboxed while this message appears?
 - Are you sure that Process Hacker is not forced to run inside any sandbox by [Forced Folders](https://www.sandboxie.com/ForceFolder) or another mechanism?

Normally, this message indicates that there is no more memory available for use within the region of memory that was allocated **to the sandboxed program**. If PH works outside the sandbox it's strange. I can't reproduce this problem.

**Comment by stdedos** [comment]
My bad, but I didn't know what support info to provide.

- `SbieSupport.dll` version will come later unfortunately - but I think it is a "recent one". I have been asking for them to get generated, but there is no "updates" or re-generated binaries "automatically".
- To my understanding, no. Sandboxie tray icon (and status window) appears clean/empty
- Yes. It has been like that forever, since I run PH for my main system. (I am not sure what would be the reason to run PH sandboxed :confused: )

**Comment by dmex** [comment]
I can't reproduce this either. You should report this issue to the sandboxie developers since there's nothing I can do about 3rd party software and their error dialogs 🙁

@stdedos 
It's probably caused by the code Avast is currently injecting into Process Hacker and the numerous changes to the nightly build.

**Comment by stdedos** [comment]
@dmex Well ... lets see when it will be appropriate to be shielded by the code injection :smile: 

I totally forgot to update on the `SbieSupport.dll` version. Which one have you tested against?
If I can find no "meaningful" leftovers on the PH directory, how you'd you recommend that I find the version from? Or, to which version should I update to, to re-test

**Comment by stdedos** [comment]
![image](https://user-images.githubusercontent.com/133706/36059661-27e949a4-0e45-11e8-9ce9-f0400b4858be.png)

**Comment by dmex** [comment]
> update on the SbieSupport.dll version

The SbieSupport.dll plugin hasn't changed since 1.0 (about 6 years ago). If you've recently started having issues with that plugin it's because 3rd party software is causing the issue 😕

**Comment by stdedos** [comment]
I updated PH and then it stopped working, not Sandboxie ==> it's not a Sandboxie issue, but a PH or PH-handling one.

I understand if you _don't want to fix it_. And I cannot blame you.

**Comment by dmex** [comment]
@stdedos 

> I updated PH and then it stopped working

Just to be clear. I recently enabled support for new security features available on Win10 including the "Microsoft signed only" policy that prevent and block various types of malicious attacks.

Sandboxie or something else is doing something that is not compatible with these security features and you're seeing an error from Sandboxie because of a problem with their software.

I can't fix their code and you need to report this problem to their developers 👍

**Comment by maskelihileci** [comment]
ProcessHacker.exe has blocked
Change name dropdown.

0ProcessHackers.exe

**Comment by OJacot-Descombes** [comment]
Removing SbieSupport.dll from the plugin folder of Process Hacker, eliminates the problem.

**Comment by stdedos** [comment]
@OJacot-Descombes sure, but, that's not the point. Then you loose the functionality 😄

**Comment by OJacot-Descombes** [comment]
@stdedos sure, but it's a workaround allowing you to run Process Hacker as long as there is no fix available. I couldn't run Process Hacker for quite a while, because I did not realize why I got this SBIE error when trying to launch Process Hacker, until I found this SbieSupport.dll plugin. I did not even know it had such a plugin.

**Comment by dmex** [comment]
>  I did not realize why I got this SBIE error when trying to launch Process Hacker

Are you trying to run Process Hacker inside a sandbox or something?

**Comment by OJacot-Descombes** [comment]
No, I am not trying to run Process Hacker in SBIE; however, when the SbieSupport.dll plugin is installed in the "plugins" subfolder of Process Hacker, then I cannot launch Process Hacker.
