### ISSUE TITLE
Unknown sorting order in Windows

### ISSUE THREAD

**Issue by TETYYS** [processhacker2/processhacker#90]
I guess it should sort by thread name, but it just groups the threads, and even not all threads into one group, and I can't really see how does it sort the windows.

![processhacker_2016-12-21_01-43-01](https://cloud.githubusercontent.com/assets/3091645/21372270/d4d5be50-c71e-11e6-884e-a6ff3eff0d9b.png)

**Comment by dmex** [comment]
Here's the sorting code:

```
BEGIN_SORT_FUNCTION(Thread)
{
    sortResult = uintptrcmp((ULONG_PTR)node1->ClientId.UniqueProcess, (ULONG_PTR)node2->ClientId.UniqueProcess);

    if (sortResult == 0)
        sortResult = uintptrcmp((ULONG_PTR)node1->ClientId.UniqueThread, (ULONG_PTR)node2->ClientId.UniqueThread);
}
END_SORT_FUNCTION
```

The sorting code is based on the View menu > Windows option (where there are hundreds of different processes that need to be grouped) instead of the Process properties > Window tab (where there are only threads).

Fixing the sorting for the Windows tab will break the main Windows option sorting for processes plus it's not really an issue now that both features include the searchbox.
